/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package membershipgui;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.geom.Rectangle2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.db.DBUser;


/**
 *
 * @author Shravan
 */
public class Printpreview extends javax.swing.JFrame implements Printable, ActionListener{

    /**
     * Creates new form Printpreview
     */
	public DBUser user;  
    public Printpreview() {
        initComponents();
       // getContentPane().setBackground(new Color(1,93,156));
    }
    public Printpreview(DBUser dbUser) {
    	user = dbUser;
        initComponents();
       // getContentPane().setBackground(new Color(1,93,156));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	ShapesJPanel shapesJPanel = new ShapesJPanel(user);
        jFrame1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

       
        jFrame1.add(shapesJPanel);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        
        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("Print");
   
        
        jButton1.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		jButton1ActionPerformed(evt);
        	}
        });
        
/*        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        */

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(819, 1000));
        //getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(169, 631, 73, 42);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Print Preview");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 5, 135, 30);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(521, 650, 55, 23);

        add(shapesJPanel);
        setVisible(true);
        repaint();
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

		PrinterJob job = PrinterJob.getPrinterJob(); //Get the printer's job list
		job.setPrintable(this); //We print with this class (btnPrintAction, which implements Printable)
		if (job.printDialog() == true) { //If we clicked OK in the print dialog
			try {job.print();} catch (PrinterException ex){
				//It did not work (PrinterException thrown), so add any error handling routines.
			}
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Add_Member am = new Add_Member();
        am.setVisible(true);
        close();
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Printpreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Printpreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Printpreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Printpreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Printpreview().setVisible(true);
            	Printpreview printpreview = new Printpreview();
                printpreview.setVisible(true);
                printpreview.setExtendedState(printpreview.MAXIMIZED_BOTH);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
	public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
		
		if (pageIndex>0){return NO_SUCH_PAGE;}
		Graphics2D g2d = ( Graphics2D ) graphics; // cast g to Graphics2D
		   
        
		
		   
	    SimpleDateFormat sdf = new SimpleDateFormat("dd/M/yyyy");
		String date = sdf.format(new Date());  
	
        g2d.setPaint( Color.BLACK );      
        g2d.setFont(new Font("Monospaced", Font.BOLD, 26));
        g2d.drawString("Silverline Sports Club", 110, 130);
        g2d.setStroke( new BasicStroke( 3.0f ) );            
        g2d.draw( new Rectangle2D.Double( 80, 90, 400, 500 ) );
        g2d.setStroke( new BasicStroke( 3.0f ) );  
        g2d.drawLine(80, 150, 480, 150  );
        g2d.setFont(new Font("Calibri", Font.BOLD, 16));
        g2d.drawString("Receipt", 260, 170);
        g2d.setFont(new Font("Calibri", Font.BOLD, 16));
        g2d.drawString("Date : ", 350, 200);
        g2d.drawString(date, 400, 200);        
        g2d.setFont(new Font("Calibri", Font.PLAIN, 20));
        g2d.drawString("Name              : "+user.getFirstname()+" "+user.getSurname(), 110, 250);
        g2d.drawString("Membership ID     : "+user.getMemberID(), 110, 300);
        g2d.drawString("Subscription Type : "+user.getSubscriptionType(), 110, 350);
        g2d.drawString("Payment Amount    : "+user.getAmountPaid(), 110, 400);
        g2d.setStroke( new BasicStroke( 2.0f ) );
        g2d.drawLine(350, 480, 450, 480  );
        g2d.setFont(new Font("Calibri", Font.BOLD, 16));
        g2d.drawString("Authorised Signature", 320, 500);
        return PAGE_EXISTS;
	}

	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		
	}




	private void close(){

	    WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
	    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
	 }	
	
}
